version: '3.4'

services:
  flask_app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    env_file:
      - .env

  aston_bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.discord
    depends_on:
      - flask_app
    env_file:
      - .env
