version: '3.4'

services:
  database:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=DiscordDatabase

  flask_app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "10080:5000"
    depends_on:
      - database

  aston_bot:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.discord
    depends_on:
      - flask_app