version: '3.4'

services:
  flask_app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10080:5000"
    env_file:
      - .env

  aston_bot:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.discord
    depends_on:
      - flask_app
    environment: 
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
